import {openPdfPage} from './rules-reader.js';
import {categories,normalize,matchesCategory,rankResults,splitIntents} from './rules-search.js';
const $=id=>document.getElementById(id);const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;};
let dataSha256,data,rules,byId,docById,category='all',query='',mode='semantic',worker,serial=0,generation=0,busy=false,lastQuery='',expanded=false,lastGroups=[],semanticReady=false;const pending=new Map(),cache=new Map();
const link=(text,url,download=false)=>{const a=node('a',text);a.href=url;if(download)a.download='';else{a.target='_blank';a.rel='noopener noreferrer';}return a;};
function sourceLinks(rule){const div=node('div',undefined,'result-actions');for(let i=0;i<rule.pdfPages.length;i++){const a=node('a',`查看原文 · PDF ${rule.pdfPages[i]} / 正文 ${rule.printedPages[i]}`);a.href=rule.sourcePdfUrl+'#page='+rule.pdfPages[i];a.dataset.pdfPage=rule.pdfPages[i];a.addEventListener('click',e=>{e.preventDefault();openPdfPage(rule.documentId,rule.pdfPages[i],rule.printedPages[i],true);});div.append(a);}return div;}
function figureButton(figure){const button=node('button',undefined,'figure-button');button.type='button';button.setAttribute('aria-label','放大：'+figure.description);const img=node('img');img.src=figure.url;img.alt=figure.description;img.loading='lazy';img.width=778;img.height=1100;button.append(img);button.addEventListener('click',()=>openFigure(figure,button));return button;}
function ruleCard(rule,related=false){const card=node('article',undefined,'result-card');card.dataset.ruleId=rule.id;card.append(node('h3',rule.titleZh+(related?' · 关联条款':'')),node('p','中文说明：'+rule.summaryZh),node('p','适用对象 / 场景：'+rule.applicability),node('p',rule.conditions,'source-note'),node('p',`${docById.get(rule.documentId).name} · 条款 ${rule.ruleNumber} · PDF 页序 ${rule.pdfPages.join('、')} · 正文页码 ${rule.printedPages.join('、')}`,'reference'));
const details=node('details'),summary=node('summary','展开原文');details.append(summary,node('p',rule.titleOriginal,'reference'),node('pre',rule.originalText,'original-text'));card.append(details,sourceLinks(rule));if(rule.figureReferences.length){const figures=node('details');figures.append(node('summary','查看对应着装图示'));const list=node('div',undefined,'figure-list');for(const page of rule.figureReferences){const f=data.figures.find(f=>f.page===page);const figure=node('figure');figure.append(figureButton(f),node('figcaption',`附录 A · PDF 第 ${page} 页：${f.description}`));list.append(figure);}figures.append(list);card.append(figures);}return card;}
function clearFilterButton(){ $('clear-filter').hidden=category==='all';$('filter-status').textContent=category==='all'?'当前范围：全部三份文件':`当前筛选：${categories[category]}（搜索词保留）`;for(const b of $('category-filters').children)b.setAttribute('aria-pressed',String(b.dataset.category===category));}
function renderGroups(groups){lastGroups=groups;$('results').replaceChildren();let hiddenCount=0;for(const group of groups){let rows=group.rows.filter(row=>matchesCategory(byId.get(row.id),category));const heading=node('h3',group.title);$('results').append(heading);if(!rows.length){$('results').append(node('p',group.rows.length?'此筛选范围没有结果，清除筛选可查看全库相关条款。':'暂未找到可展示条款。'));continue;}const shown=expanded?rows:rows.slice(0,5);hiddenCount+=rows.length-shown.length;const used=new Set(shown.map(x=>x.id));for(const row of shown)$('results').append(ruleCard(byId.get(row.id)));const relatedIds=[...new Set(shown.flatMap(row=>byId.get(row.id).relatedRuleIds))].filter(id=>!used.has(id)&&matchesCategory(byId.get(id),category));if(relatedIds.length){const related=node('details');related.append(node('summary',`其他相关规则 · ${relatedIds.length} 条关联条款`));related.addEventListener('toggle',()=>{if(related.open&&related.children.length===1)for(const id of relatedIds)related.append(ruleCard(byId.get(id),true));});$('results').append(related);}}
$('more-results').hidden=hiddenCount===0;$('more-results').textContent=`展开其他相关规则（${hiddenCount} 条）`;}
function groupedRows(intent,rows){if(/罚款|fine|compound|申诉|appeal/i.test(intent)&&rows.length){return data.documents.map(doc=>({title:`${doc.name} · ${intent}`,rows:rows.filter(r=>byId.get(r.id).documentId===doc.id)})).filter(g=>g.rows.length);}return[{title:query?`最相关规则 · ${intent}`:'先看看常见规则',rows}];}
function ordinaryGroups(intents){return intents.flatMap(intent=>groupedRows(intent,rankResults(intent,rules)));}
function semanticSearch(text){if(cache.has(text))return Promise.resolve(cache.get(text));if(!worker){worker=new Worker('rules-semantic-worker.js',{type:'module'});worker.onmessage=({data:m})=>{if(m.type==='ready'){semanticReady=true;return;}if(m.type==='progress'){if(busy)$('search-status').textContent=`普通搜索结果已显示；正在加载语义模型 ${m.progress}%…`;return;}const request=pending.get(m.requestId);if(!request)return;clearTimeout(request.timer);pending.delete(m.requestId);if(m.type==='error')request.reject(Error(m.message));else{cache.set(request.query,m.scores);request.resolve(m.scores);}};worker.onerror=()=>{for(const r of pending.values()){clearTimeout(r.timer);r.reject(Error('语义模型未能运行'));}pending.clear();worker.terminate();worker=null;semanticReady=false;};}return new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{pending.delete(id);reject(Error('语义模型加载超时'));},120000);pending.set(id,{resolve,reject,timer,query:text});worker.postMessage({requestId:id,query:text,dataSha256});});}
async function search(){if(!data){$('search-status').textContent='规则资料未加载，搜索不可用。请使用下方完整 PDF。';return;}const value=$('rule-query').value.trim();if(!value){$('search-status').textContent='请输入想查的问题。';return;}if(!/[\p{L}\p{N}]/u.test(value)||/^([\p{L}\p{N}])\1{5,}$/u.test(value)){$('search-status').textContent='请换一种描述，例如“宿舍可以做饭吗”。';return;}if(/^(?:这样可以吗|可以吗|能不能|怎么办|这个|那样|允许吗|这个允许吗)[?？。!！]*$/.test(value)){generation++;busy=false;$('search-status').textContent='问题还不明确，请补充你想做什么、在哪里，例如“在宿舍做饭可以吗”。';return;}if(busy&&value===lastQuery)return;const ticket=++generation;lastQuery=value;query=value;expanded=false;busy=true;const intents=splitIntents(value);const groups=ordinaryGroups(intents);renderGroups(groups);$('search-status').textContent=mode==='ordinary'?'普通搜索结果（语义检索未启用）。未命中不代表校规未表明。':'普通搜索结果已显示；正在进行语义检索…';if(mode==='ordinary'){busy=false;return;}try{const scores=await Promise.all(intents.map(semanticSearch));if(ticket!==generation)return;const semanticGroups=intents.flatMap((intent,i)=>groupedRows(intent,rankResults(intent,rules,scores[i])));renderGroups(semanticGroups);const noResult=semanticGroups.every(g=>g.rows.length===0);if(noResult){$('search-status').textContent='该规则未在校规中表明，你也可以自行查阅校规';$('results').replaceChildren(node('p','此结果仅表示在当前收录的三份文件中未找到明确依据，不表示行为已获允许。'));const a=node('a','查看完整校规');a.href='#documents';$('results').append(a);}else $('search-status').textContent=semanticGroups.some(g=>g.rows.some(r=>r.lexical>=2))?'找到相关条款。请按适用场景、条件与例外核对原文；检索结果不自动判定可以/不可以。':'找到可能相关的规定，未找到针对该情况的明确说明。请核对原文条件，或换一种描述缩小范围。';}catch(error){if(ticket!==generation)return;renderGroups(groups);$('search-status').textContent='语义搜索不可用，已降级为普通搜索。'+error.message+'。可继续查关键词或查看完整 PDF。';}finally{if(ticket===generation)busy=false;}}
function browseCategory(){expanded=false;if(query)renderGroups(lastGroups);else{const ids=category==='all'?['hostel-10','hostel-11','dress-7']:rules.filter(r=>matchesCategory(r,category)).map(r=>r.id);renderGroups([{title:category==='all'?'先看看常见规则':categories[category],rows:ids.map(id=>({id}))}]);$('search-status').textContent='可按分类浏览，或输入问题跨三份文件搜索。';}}
function documents(){const host=$('document-list');host.replaceChildren();for(const doc of data.documents){const article=node('article',undefined,'document-card');article.append(node('h3',doc.name),node('p',`${doc.pageCount} 页 · 收录日期 ${data.collectedAt}`,'reference'),node('p',doc.version,'source-note'));const actions=node('div',undefined,'result-actions');actions.append(link('打开完整 PDF',doc.pdfUrl),link('下载原文件',doc.pdfUrl,true));article.append(actions);const toc=node('details');toc.append(node('summary','按原文件章节查阅全部条款'));const sections=[...new Set(rules.filter(r=>r.documentId===doc.id).map(r=>r.section))];for(const section of sections){const details=node('details');details.append(node('summary',section));for(const rule of rules.filter(r=>r.documentId===doc.id&&r.section===section)){const item=node('details');item.append(node('summary',`${rule.ruleNumber} · ${rule.titleZh} / ${rule.titleOriginal}`));item.addEventListener('toggle',()=>{if(item.open&&item.children.length===1)item.append(ruleCard(rule));});details.append(item);}toc.append(details);}article.append(toc);const archive=node('details');archive.append(node('summary',`按 PDF 页序查看完整提取文本（${doc.pageCount} 页，含目录及版本表）`));archive.addEventListener('toggle',()=>{if(!archive.open||archive.children.length>1)return;for(const page of doc.pages){const detail=node('details');detail.append(node('summary',`PDF 第 ${page.pdfPage} 页${doc.id==='hostel'&&page.pdfPage>=7?' · 正文第 '+(page.pdfPage-6)+' 页':''}`),node('pre',page.text.trim()||'本页无可提取文字；封面或空白页请查看原 PDF。','original-text'),link('打开该原始页',doc.pdfUrl+'#page='+page.pdfPage));if(doc.id==='dress'&&page.pdfPage>=20&&page.pdfPage<=26){const f=data.figures.find(f=>f.page===page.pdfPage);detail.append(node('p',f.description),figureButton(f));}archive.append(detail);}});article.append(archive);if(doc.id==='dress'){const gallery=node('details');gallery.append(node('summary','附录 A：查看全部 7 页着装图示'));const list=node('div',undefined,'figure-list');for(const f of data.figures){const fig=node('figure');fig.append(figureButton(f),node('figcaption',f.description),link(`原 PDF 第 ${f.page} 页`,doc.pdfUrl+'#page='+f.page));list.append(fig);}gallery.append(list);article.append(gallery);}host.append(article);}}
const dialog=$('figure-dialog');let opener;
function openFigure(figure,button){opener=button;$('figure-caption').textContent=`着装附录 · PDF 第 ${figure.page} 页`;$('figure-image').src=figure.url;$('figure-image').alt=figure.description;dialog.showModal();document.body.classList.add('viewer-open');}
$('close-figure').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('viewer-open');opener?.focus();});dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
$('rule-search').addEventListener('submit',e=>{e.preventDefault();search();});$('ordinary-search').addEventListener('click',()=>{mode=mode==='ordinary'?'semantic':'ordinary';$('ordinary-search').textContent=mode==='ordinary'?'启用语义搜索（首次约 118 MB）':'仅使用普通搜索';generation++;busy=false;if($('rule-query').value.trim())search();else $('search-status').textContent=mode==='ordinary'?'已切换普通搜索。':'已启用语义搜索，提交问题时加载。';});$('common-queries').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){$('rule-query').value=e.target.textContent;search();}});$('more-results').addEventListener('click',()=>{expanded=true;renderGroups(lastGroups);});$('clear-filter').addEventListener('click',()=>{category='all';clearFilterButton();browseCategory();});
for(const [key,label] of Object.entries(categories)){const b=node('button',label);b.dataset.category=key;b.setAttribute('aria-pressed',String(key==='all'));b.addEventListener('click',()=>{category=key;clearFilterButton();browseCategory();});$('category-filters').append(b);}
try{const response=await fetch('rules-assets/rules-data.json');if(!response.ok)throw Error('HTTP '+response.status);const bytes=await response.arrayBuffer();dataSha256=[...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(x=>x.toString(16).padStart(2,"0")).join("");data=JSON.parse(new TextDecoder().decode(bytes));rules=data.rules;byId=new Map(rules.map(r=>[r.id,r]));docById=new Map(data.documents.map(d=>[d.id,d]));if(!rules.length||byId.size!==rules.length)throw Error('资料完整性检查失败');documents();browseCategory();}catch(e){$('search-status').textContent='规则资料加载失败，搜索不可用。请通过下方完整 PDF 查阅。';}
