const $=id=>document.getElementById(id);
const sources={discipline:{title:'校规',url:'rules-assets/discipline.pdf',pages:40},hostel:{title:'宿舍规定',url:'rules-assets/hostel.pdf',pages:35},dress:{title:'着装规范',url:'rules-assets/dress.pdf',pages:27}};
let current='discipline',pageNumber=1,zoom=1,pdf,loadingTask,renderTask,library,version=0,paintVersion=0;
const tabs=[...document.querySelectorAll('[data-document]')];
function updateTarget(printed){const source=sources[current];$('pdf-target').textContent=`目标：${source.title} · PDF 第 ${pageNumber} 页`+(printed!=null?` · 正文印刷第 ${printed} 页`:current==='hostel'&&pageNumber>=7?` · 正文印刷第 ${pageNumber-6} 页`:current==='hostel'?' · 封面 / 目录':pageNumber<=2||current==='discipline'&&pageNumber===40?' · 封面 / 空白页，无正文印刷页码':' · 正文页码与 PDF 页序一致');$('pdf-open').href=source.url+'#page='+pageNumber;$('pdf-download').href=source.url;$('pdf-page-number').value=pageNumber;$('pdf-page-number').max=pdf?.numPages||source.pages;$('pdf-page-total').textContent='/ '+(pdf?.numPages||source.pages);$('pdf-prev').disabled=!pdf||pageNumber<=1;$('pdf-next').disabled=!pdf||pageNumber>=pdf.numPages;$('pdf-zoom-label').textContent=Math.round(zoom*100)+'%';}
async function renderPage(){if(!pdf)return;const ticket=++paintVersion;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}}if(ticket!==paintVersion)return;try{const page=await pdf.getPage(pageNumber);if(ticket!==paintVersion)return;const box=$('pdf-viewport'),base=page.getViewport({scale:1}),scale=Math.max(160,box.clientWidth-24)/base.width*zoom,viewport=page.getViewport({scale});const ratio=Math.min(devicePixelRatio||1,2),canvas=$('pdf-canvas');canvas.width=Math.ceil(viewport.width*ratio);canvas.height=Math.ceil(viewport.height*ratio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';canvas.setAttribute('aria-label',`${sources[current].title} PDF 第 ${pageNumber} 页`);renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});await renderTask.promise;if(ticket!==paintVersion)return;$('pdf-status').textContent=`${sources[current].title} · 第 ${pageNumber} / ${pdf.numPages} 页`;$('pdf-canvas').hidden=false;box.scrollTo(0,0);}catch(e){if(ticket!==paintVersion||e.name==='RenderingCancelledException')return;$('pdf-status').textContent='文档无法内嵌或渲染，请打开原文件并按目标页码查阅。';$('pdf-canvas').hidden=true;}}
export async function openPdfPage(id,page=1,printed,scroll=false){if(!sources[id])return;const same=id===current;current=id;pageNumber=Math.max(1,Math.min(sources[id].pages,Number(page)||1));tabs.forEach(tab=>{const selected=tab.dataset.document===id;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;});$('pdf-panel').setAttribute('aria-labelledby','pdf-tab-'+id);updateTarget(printed);if(scroll){$('documents').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});$('pdf-panel').tabIndex=-1;$('pdf-panel').focus({preventScroll:true});}if(same&&pdf){await renderPage();return;}const ticket=++version;paintVersion++;renderTask?.cancel();$('pdf-canvas').hidden=true;$('pdf-status').textContent='正在加载'+sources[id].title+'…';pdf=null;updateTarget(printed);try{if(loadingTask)await loadingTask.destroy();if(ticket!==version)return;library??=import('./rules-assets/pdfjs/pdf.js');const pdfjs=await library;if(ticket!==version)return;pdfjs.GlobalWorkerOptions.workerSrc=new URL('./rules-assets/pdfjs/pdf.worker.js',import.meta.url).href;loadingTask=pdfjs.getDocument({url:sources[id].url,standardFontDataUrl:new URL('./rules-assets/pdfjs/standard_fonts/',import.meta.url).href,useWasm:false,isEvalSupported:false});const loaded=await loadingTask.promise;if(ticket!==version){await loaded.destroy();return;}pdf=loaded;updateTarget(printed);await renderPage();}catch(e){if(ticket!==version)return;$('pdf-status').textContent='文档查看器加载失败，请打开原文件并按目标页码查阅。';$('pdf-canvas').hidden=true;}}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>openPdfPage(tab.dataset.document));tab.addEventListener('keydown',e=>{const keys=['ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowLeft'?-1:1)+3)%3;tabs[next].focus();openPdfPage(tabs[next].dataset.document);});});
$('pdf-prev').addEventListener('click',()=>openPdfPage(current,pageNumber-1));$('pdf-next').addEventListener('click',()=>openPdfPage(current,pageNumber+1));$('pdf-page-number').addEventListener('change',()=>openPdfPage(current,$('pdf-page-number').value));$('pdf-page-number').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();openPdfPage(current,e.target.value);}});
for(const [id,delta]of [['pdf-zoom-in',.25],['pdf-zoom-out',-.25]])$(id).addEventListener('click',()=>{zoom=Math.max(.5,Math.min(3,zoom+delta));updateTarget();renderPage();});$('pdf-fit').addEventListener('click',()=>{zoom=1;updateTarget();renderPage();});let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>renderPage(),120);}).observe($('pdf-viewport'));
const header=document.querySelector('.topbar');new ResizeObserver(()=>document.documentElement.style.setProperty('--rules-header-height',header.offsetHeight+'px')).observe(header);
export function initializeReader(){return openPdfPage('discipline');}initializeReader();
